### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by doe300** [doe300/Minimal-Todo#1]
Changes to be implemented:
- [ ] rewrite to make use of new API features/better coding style
- [ ] rewrite storing/loading of ToDo-Items
- add ToDo-groups
  - [ ] add input-field to ToDos for group-name (optional). Suggest all existing groups on input
  - [ ] group and color ToDos by group
- add widget to home-screen
  - [ ] add widget containing the ToDo-Items, on click open Minimal-TODO
  - [ ] make displayed ToDos for widget configurable. Last X ToDos (created), next ToDos (reminder time), ...
- add option to export ToDos to calendar (only ToDos with reminder), add calendar-event for exported ToDo-Items
